const _import = require('~Router/_import_' + process.env.NODE_ENV);
//所挂载的 page 组件名
const parentRouterCompName = "OblArticlePage" ;
let basePath = 'article/' ;
const ArticleRouter = [
    {
        path:basePath+'create',
        component:_import('index/obl/article/create/OblArticleCreateView'),
        name:'articleCreate',
        meta:{
            title:'写文章',icon:"reconciliation",keepAliveFlag:true,
            parentRouterCompName,
            selfCompName:'ArticleCreateView'
        }
    },
    {
        path:basePath+'all_list',
        component:_import('index/obl/article/allList/OblArticleAllListView'),
        name:'articleAllList',
        meta:{
            title:'文章列表',icon:"bars",keepAliveFlag:true,
            parentRouterCompName,
            selfCompName:'ArticleAllListView'
        }
    },
    {
        path:basePath+'my_create_list',
        component:_import('index/obl/article/myCreateList/OblArticleMyCreateListView'),
        name:'articleMyCreateList',
        meta:{
            title:'我的文章',icon:"bars",keepAliveFlag:true,
            parentRouterCompName,
            selfCompName:'ArticleMyCreateListView'
        }
    },
    {
        path:basePath+'tag',
        component:_import('index/obl/article/tag/OblArticleTagView'),
        name:'articleTag',
        meta:{
            title:'文章标签',icon:"reconciliation",keepAliveFlag:true,
            parentRouterCompName,
            selfCompName:'ArticleTagView'
        }
    },
    {
        path:basePath+'category',
        component:_import('index/obl/article/category/OblArticleCategoryView'),
        name:'articleCategory',
        meta:{
            title:'文章分类',icon:"reconciliation",keepAliveFlag:true,
            parentRouterCompName,
            selfCompName:'ArticleCategoryView'
        }
    },
    {
        path:basePath+'my_draft_list',
        component:_import('index/obl/article/myDraftList/OblArticleMyDraftListView'),
        name:'articleMyDraftList',
        meta:{
            title:'草稿箱',icon:"bars",keepAliveFlag:true,
            parentRouterCompName,
            selfCompName:'ArticleMyDraftListView'
        }
    },
    {
        path:basePath+'display',
        component:_import('index/obl/article/display/OblArticleDisplayView'),
        name:'articleDisplay',
        meta:{
            title:'文章展示',icon:"book",keepAliveFlag:true,
            visitLimit:false ,
            parentRouterCompName,
            selfCompName:'ArticleTagView'
        }
    },
    {
        path:basePath+'recommend',
        component:_import('index/obl/article/recommend/OblArticleRecommendView'),
        name:'articleRecommendView',
        meta:{
            title:'文章推荐',icon:"check-square",keepAliveFlag:true,
            parentRouterCompName,
            selfCompName:'OblArticleRecommendView'
        }
    },
    {
        path:basePath+'recommend_delay_record',
        component:_import('index/obl/article/recommendDelay/OblArticleRecommendDelayRecordView'),
        name:'articleRecommendDelayRecordView',
        meta:{
            title:'文章推荐调整记录',icon:"right-square",keepAliveFlag:true,
            parentRouterCompName,
            selfCompName:'OblArticleRecommendDelayRecordView'
        }
    },
];
export default ArticleRouter ;
